name: prod

on:
  release:
    types: [created]

jobs:

  prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://jewl.app/
    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Create deployment
      run: doctl apps create-deployment d7ae2b6d-cf79-41d2-a60a-919aa2152138 --wait
